language: go
go:
- 1.14.4
install:
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
- sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - main
env:
  global:
  - secure: gWc+iUGRxZ+jNyz6QRIrbVUmNWecNYld1ptVqRr4tqvYFTis3lKvC2fj3nkaEJ0TH86gR6FXGx4dDcTtY6RGYjDY6xyv9mf01RvomBhcFMAFcxbQXVud4x2mb5E8NA8CykROh1VWUGIbzyH/k/+g5/+pBXiFHO0NTYyVv1EzvJyVbMOElXHB2KoO8QvM41FxX4/fpMXEPKO8r8XH8t9ym3/OPbNt+Gq3bkIxi5NOW6V9KEqpe+JfOxVCoCGw3Xvr4ZrtZv2er6BTUIeTz/A4B6T9a9ZB0aLqUkvYpMxqZR1z7UKjrSz+s3pTY9B43tMFkuCWyVVFuWtVzzG/8TYFV20JMkojkfh6LnlP3AmTdQYZWB0iNZ8TQJVgTLYLL++OBHuxG1Lr1FuULPGv7YaqrS62t+QCxPPky64WkwGG6WiCogRwCndQRM/xMPt0yhlBnSGikYic62rGL1KT3muRFGsDIwXKFenuliCyjBTxwOiFmqet7cfn4Ei9BD4GWKmJU/Vpr+Gvn/of57AzSnlxX33YHUAnBBCQ2Fh48twmUh8AJ9lHAjF8l5nEnkp6rwFUZCjYyalkggufiEBDTGMx/dYVR2CZYloEiz9K39O2bl3Cw2noLFXzFwPMQGlwungWkaXFS87CSXqZjlENd6T1bkqDX77f4Cmg90cCoTcQfks=
  - secure: LiMf877Jfwu6ceeS81eGDuP4tGA7siD3kgEZxJjrpW+aXl8j1GBUG5wRz8o8kABjO4Pq4g3EhYNtYfHqWaRPeUGj5YsFGKXAkmqQp3KM1SF6OUVOZC40Eg8Imap1N+tPk3ag7rJfgxJHHj8Rm5S/n1fWhQG4dPFbrw6YZSOPTm3e2xf1v4fw2dNWp4+fHZg4dKUK14wzjjEUQuFtdGHEQj3wnHaN2djAtRePuCMmtk6HDBC9OcQdXja675geWk0Z0remoYArCIbQKV3jVBrA1orjNQe3UKqWSQ1HArMzCDTkJv3ZYhRey8AqWqx08kqoMW4hPnQE7XVG0XRumRCqgoRVV1XlIvMBLyPvPEx28Nh4XzvNV9ZlquvgivfMiIetxdxHn9z80MQ0W3yuMxuj5RbWf6JLkLWjr52nElpSuZOOp/U6NYb3i32ijyPnVgRCRivNlo3gDlMXKcwd8OPoc/J6x3x6uqYYCpHetDL71thyNw9V+5kZO6L6lw02SzHcADX0CBhqGDCYVWpDx/6PgJkxJG/wtfUskB9jFz+wR80faKD88yG/yTyo357kWDNy3uxiIPaGWssCBGPLNe+LrmFtpVTfFIzMttvgh6LetsAr8s7Fd6wrpFztNWWVrosY4cY0izb1mS7QcYBnFDUF0dgrCTXFIY2GOu6JN7pwW6k=
